### ISSUE TITLE
Some remarks about your license texts

### ISSUE THREAD

**Issue by pmario** [kookma/TW-Gatha#1]
Just some remarks.

Your plugin should have a readme, license and a history tab ;) see: https://kookma.github.io/TW-Gatha/#%24%3A%2Fplugins%2Fkookma%2Fgatha

Your license full text is included in every plugin, which from my point of view is a bit of bloat. ... BUT that's only my opinion, that I wanted to let you know. ... It's perfectly fine, if you ignore it!

I'm using something like this: https://wikilabs.github.io/editions/bundler/#%24%3A%2Fplugins%2Fwikilabs%2Fbundler%2Flicense, because some of my plugins are small and the full license text would need more space then the plugin itself.

**Comment by kookma** [comment]
Hi Mario,

> Your plugin should have a readme, license and a history tab

 Many thanks, It is strange I have forgotten this!


> I'm using something like this: https://wikilabs.github.io/editions/bundler/#%24%3A%2Fplugins%2Fwikilabs%2Fbundler%2Flicense, because some of my plugins are small and the full license text would need more space then the plugin itself.

Good idea! Thank you
