### ISSUE TITLE
is it not support load theme or make theme plugin

### ISSUE THREAD

**Issue by oeyoews** [kookma/TW-Gatha#3]
when i drag a `notebook` theme to tiddlywiki, and load it use TW-Gatha, I got this, all tiddlers is empty

![image](https://user-images.githubusercontent.com/72405338/180710212-86ccf851-1e05-4e26-9fe0-6949eacd8fb2.png)

**Comment by kookma** [comment]
I will give a try and back to you!
By the way can you test some official theme from https://tiddlywiki.com/?

There may be an issue with notebook.

**Comment by kookma** [comment]
I checked this. Gatha works as expected.
Please note that, Tiddlywiki on loading a theme load its tiddler.
So first make your Theme active (theme in use) and then load it from Gatha

Example
Here I opened the SnowWhite from $:/ConteolPanel-->Plugins--> Themes
![image](https://user-images.githubusercontent.com/830394/180780200-14c4925a-8559-4ecf-9e7f-459823dda08f.png)

See the tiddler is missing! Now make SnowWhite the active theme and see the tiddler.

**Comment by kookma** [comment]
See it is opened in Gatha

![image](https://user-images.githubusercontent.com/830394/180781417-4bd0a8e6-5b19-43ec-aed2-104fe04baf8c.png)

and the base

![image](https://user-images.githubusercontent.com/830394/180781479-f175e181-fab7-46b4-8ea2-5e692bb33e84.png)
