### ISSUE TITLE
feature: remove redundant fields

### ISSUE THREAD

**Issue by oeyoews** [kookma/TW-Gatha#4]
For exported plugins, we should remove redundant fields， like creater, created, modified, and some empty field, keep only required fields. can gatha do that?

**Comment by kookma** [comment]
It is possible to do that! But this should be optional, some author may like to keep their name.

Right now, is responsibility of author to that. I myself use Commander to do the job! Normally for a plugin with 50kB, removing created/modified decrease the size of plugin by 2kB.

**Comment by oeyoews** [comment]
Yes, but I always get the modified field again, after clicking Disselect all to remove `$:/tags/Commander/Working` tag

**Comment by kookma** [comment]
First turn off the timestamp from right sidebar/tools

**Comment by oeyoews** [comment]
damn, how could I forget this. Thank you

**Comment by kookma** [comment]
By the way I will add an option to Gatha settings, allow user to check some checkboxes to remove created/modified/creator/modifier before packaging.

No need to reopen the issue. I add this to my todolist
