### ISSUE TITLE
Load plugin dropdown menu does not open

### ISSUE THREAD

**Issue by bp1189** [kookma/TW-Gatha#5]
After enabling the _Load Plugin_ button in More > Gatha > Show load plug-in button, click _Load Plugin_ on main Gatha tab, click on the drop-down menu, and nothing happens. I tried this on TiddlyWiki.com and got the same result.

Issue happens on Chrome v.105 on Chrome OS. It seems to work fine on Android using Andtidwiki and Chrome.

**Comment by kookma** [comment]
I doubt this is a TW issue?
Can you check some drop down examples (those uses $select widget) to see if they work on Chrome OS?
I myself have no access to Chrome OS. But I tested on Chrome 105 / Win 10 and Gatha works as expected.

**Comment by bp1189** [comment]
I tried it out on another Chromebook and it works fine. I think it's an
issue with the version of Chrome on the other one, because the Chromebook
is past its auto-update expiration and I'm using the Lacros browser (same
as Chrome, but it is separated from the OS). Sorry about the confusion!
