### ISSUE TITLE
[BUG] Some UI elements do not appear

### ISSUE THREAD

**Issue by CodaCodr** [kookma/TW-Gatha#6]
Hi @kookma 

I finally installed Gatha but I am not seeing the search/filter button next to **Extra tiddlers** so the **Gatha Add Bulk of Extra Tiddlers** cannot be used.

![image](https://user-images.githubusercontent.com/436812/216074247-2473c5b4-437a-4052-ad29-e510407b5694.png)

Firefox latest, TW 5.2.5

**Comment by kookma** [comment]
Hi @CodaCodr 
It is off by default. Open Settings (you can do it from Sidebar->More->Gatha or got through $:/ControlPanle->Settings) and turn it on!

**Comment by CodaCodr** [comment]
Ha! Thanks. I never saw mention of that reading the tutorial.
