### ISSUE TITLE
 the add bulk tiddlers  button doesn't work

### ISSUE THREAD

**Issue by xtban** [kookma/TW-Gatha#7]
hello,kookma

I have a problem when i ues the **add bulk tiddlers  function** , shows in the image .

when i clicked the button,it did not add the filtered tiddlers into the extra tiddler list in one-time ,so i had to drag every tiddler  .  

i don't know if there is something wrong in the code , please check it .

and the `</div>` seems unnecessary.

![image](https://github.com/kookma/TW-Gatha/assets/56251516/1fb96eb3-ab91-4244-9099-0e7106e585db)

**Comment by kookma** [comment]
Thank you for reporting this issue.
Let me to investigate.
By the way child you try your example on the demo site and let me the result

**Comment by xtban** [comment]
[demo_bxt_myKatex_v0.0.1_20230729.txt](https://github.com/kookma/TW-Gatha/files/12206369/demo_bxt_myKatex_v0.0.1_20230729.txt)

change the suffix , from `.txt` to `.html`

**Comment by kookma** [comment]
I confirm the bug. Please let me to push an update, hopefully in the early next week.

**Comment by kookma** [comment]
Issue fixed. See new demo.
This is not a new version. This only removed uglify plugin for compressing the Gatha.
